site_name: jv [jawa] - Java Sugar Language
site_description: jv言語（やわ-らんぐ）は、読みやすいJava 25ソースコードにコンパイルされるJava Sugar Language
site_url: https://project-jvlang.github.io/
repo_url: https://github.com/project-jvlang/jv-lang
repo_name: project-jvlang/jv-lang

theme:
  name: material
  language: ja
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang:
        - ja
        - en

nav:
  - ホーム: index.md
  - はじめに:
    - クイックスタート: getting-started.md
    - インストール: installation.md
  - 言語ガイド:
    - 言語仕様: language-spec.md
    - 言語ガイド: language-guide.md
    - Javaとの相互運用: java-interop.md
  - 開発:
    - アーキテクチャ: architecture.md
    - プロジェクト構造: project-structure.md
    - CLIリファレンス: cli-reference.md
    - サンプル注釈: sample-annotation.md
  - コントリビューション:
    - 貢献ガイド: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/project-jvlang/jv-lang
    - icon: fontawesome/solid/coffee
      link: https://buymeacoffee.com/asopitechia

copyright: Copyright &copy; 2025 jv Language Project